[Modem_config]
host = ""
username = ""
password = ""
CpeModel = "" # use "technicolor, "zteh267a" , "openwrt" to select CPE

[Discord_config]
"Api key" = "" #Consult Discord Documentation on how to obtain the API key for a bot
Admin_ID = ""
Channel_ID = ""

["Database Config"]
DB_name = ""
